a=input('Digite algo: ')
print('Tipo primitivo: ', type(a))
print('Tem apenas espaços: ',a.isspace())
print('É um número? ',a.isnumeric())
print('É alfabético? ', a.isalpha())
print('É alfanumérico? ',a.isalnum())
print('Está maiúsculo? ',a.isupper())
print('Está minúsculo? ', a.islower())
print('É capitalizada? ',a.istitle())